### ISSUE TITLE
Weird issue with AWS Lambda (NodeJS 6.10)

### ISSUE THREAD

**Issue by gavinharriscolab** [rh389/dynamodb-geo.js#15]
I am getting this odd error when trying to perform a "queryRadius". Works great locally (on same version of NodeJS):

    const parameters = {
            RadiusInMeter: 10000,
            CenterPoint: {
                latitude: -32.8718529,
                longitude: 151.2268219
            }
    };

    myGeoTableManager.queryRadius(parameters)
        .then( points => console.log( JSON.stringify(points) )
        .catch(err => console.log(err, err.stack));

Error: [DecimalError] Invalid argument: 151.2268219-1
at Error (native)
at parseOther (/var/task/node_modules/nodes2ts/node_modules/decimal.js/decimal.js:3598:13)
at new Decimal (/var/task/node_modules/nodes2ts/node_modules/decimal.js/decimal.js:4293:55)
at Function.S1Angle.degrees (/var/task/node_modules/nodes2ts/dist/S1Angle.js:50:17)
at Function.S2LatLng.fromDegrees (/var/task/node_modules/nodes2ts/dist/S2LatLng.js:76:94)
at Function.S2Util.getBoundingLatLngRectFromQueryRadiusInput (/var/task/node_modules/dynamodb-geo/dist/s2/S2Util.js:26:54)
at GeoDataManager.queryRadius (/var/task/node_modules/dynamodb-geo/dist/GeoDataManager.js:204:42)
at process (/var/task/index.js:78:31)
at exports.handler (/var/task/index.js:39:5)

Any advice would be really appreciated!!
Gav

**Comment by gavinharriscolab** [comment]
Found the solution (updating here just in case someone else hits this issue).
As I was retrieving the Latitude and Longitude form the QueryString (parsed by API Gateway) they came across as Strings. Fix was to use `Number.parseFloat(lat)`.

Great library by the way! Thank you!

**Comment by wellmmer** [comment]
Thank you so much @gavinharriscolab !!

I was getting the same error and now it's working fine...
