### ISSUE TITLE
Radius Query. Cannot read property 'getRectBound' of undefined

### ISSUE THREAD

**Issue by ildar-icoosoft** [rh389/dynamodb-geo.js#8]
I get error "Cannot read property 'getRectBound' of undefined" if radius is greater than 1063652 meters.

Herre is my code:
```
myGeoTableManager.queryRadius({
    RadiusInMeter: radius,
    CenterPoint: {
        longitude: longitude,
        latitude: latitude,
    }
})
```

Here is the stack trace:
```
TypeError: Cannot read property 'getRectBound' of undefined
    at S2LatLngRect.mayIntersectC (/var/task/node_modules/nodes2ts/dist/S2LatLngRect.js:515:39)
    at S2RegionCoverer.newCandidate (/var/task/node_modules/nodes2ts/dist/S2RegionCoverer.js:210:26)
    at S2RegionCoverer.getInitialCandidates (/var/task/node_modules/nodes2ts/dist/S2RegionCoverer.js:341:36)
    at S2RegionCoverer.getCoveringInternal (/var/task/node_modules/nodes2ts/dist/S2RegionCoverer.js:366:14)
    at S2RegionCoverer.getCoveringUnion (/var/task/node_modules/nodes2ts/dist/S2RegionCoverer.js:181:14)
    at S2RegionCoverer.getCoveringCells (/var/task/node_modules/nodes2ts/dist/S2RegionCoverer.js:156:24)
    at GeoDataManager.queryRadius (/var/task/node_modules/dynamodb-geo/dist/GeoDataManager.js:205:82)
    at _callee$ (/var/task/handler.js:138:38)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:299:22)
```

**Comment by lantikchi** [comment]
I have the same issue. Is there a fix for this issue?

**Comment by rh389** [comment]
It turns out this is a bug in `nodes2ts` but the fix is still unreleased.

An ugly-but-effective option is to patch `nodes2ts` at run-time with:
```js
require('nodes2ts').S2RegionCoverer.FACE_CELLS = [0, 1, 2, 3, 4, 5].map(face => S2Cell.fromFacePosLevel(face, 0, 0));
```

Running that once before using either radius or rectangle queries should be enough. If the author of nodes2ts doesn't release a new version soon I'll add that patch to this lib.

**Comment by Sh3nr0n** [comment]
Hi sorry for the rookie question, but how do you actually "patch nodes2ts at run-time"?
More precisely, where am I supposed to require the following line of code?
Any help would be appreciated!

**Comment by rh389** [comment]
Put that line in your own app's code, anywhere you like (once per-process should be enough) as long as it's before you call `queryRadius`. 

You could put it right on the line before your `queryRadius` call if you like, but somewhere in your app's init might be neater - up to you.

**Comment by Sh3nr0n** [comment]
Thanks for your help, I'll try that!
